# shell is required due to "command" being a shell builtin
- name: Get absolute step command path # noqa command-instead-of-shell
  shell: "command -v {{ step_cli_executable }}"
  become: yes
  check_mode: no
  changed_when: no
  register: _step_cli_executable_absolute

- name: Configure certificate renewal service
  template:
    src: step-renew-systemd.service.j2
    dest: "/etc/systemd/system/{{ step_cert_renewal_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  register: _step_cert_renewal_service_register_systemd_service
  notify: restart step_cert_renewal timer

- name: Configure certificate renewal timer
  template:
    src: step-renew-systemd.timer.j2
    dest: "/etc/systemd/system/{{ step_cert_renewal_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  register: _step_cert_renewal_service_register_systemd_timer
  notify: restart step_cert_renewal timer

- name: Ensure certificate renewal service is enabled={{ step_cert_renewal_service_enabled }}
  systemd:
    name: "{{ step_cert_renewal_service_name }}.timer"
    state: started
    enabled: "{{ step_cert_renewal_service_enabled }}"
