---
step_cli_executable: step-cli
step_cli_steppath: /root/.step

#step_bootstrap_ca_url:
#step_bootstrap_fingerprint:

step_ca_root_force: no

step_ca_root_certfile: "{{ step_ca_root_certfile_defaults }}"
step_ca_root_certfile_defaults:
  path: /etc/ssl/root.crt
  mode: "644"
  owner: root
  group: root
